# The name of the workflow.
name: Ci/cd pipeline for spend smart

# Run the workflow when code is pushed to the main branch
on:
  push:
    branches:
      - main

# This is the workflow that is being run.
# ⚠️⚠️⚠️ NOTE - Backend is deployed on render.com. So, here we are only deplying frontend to Vercel. ⚠️⚠️⚠️
jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies of frontend
        run: |
          cd frontend
          npm install

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-frontend

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy frontend to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
